### ISSUE TITLE
Symlinking (additional) filestorages 

### ISSUE THREAD

**Issue by mschwemer** [helhum/typo3-secure-web#15] opened 2019-02-22 11:26 UTC
Currently the core links are hard coded in `/src/Composer/InstallerScript/WebDirectory.php`, just using `fileadmin`and `typo3temp`.

At least `fileadmin` should not be hardcoded, as this is a configurable file storage. This means the file system path of the storage can be different from `fileadmin`. 

Plus, there can be more than one filestorage, which is also not linked currently. 

Solution would be to get all filestorages from TYPO3 and all these links.

Thanks for this package (and all the others, of course).

**Comment by mschwemer** [comment] 2019-02-22 11:30
A solution might be this commit in a fork: 

https://github.com/oemmes/typo3-secure-web/commit/40be2ddd5cbff97bfce40a1afa0ee91e61bb97fb

But done automagically would be better. :-)

**Comment by mschwemer** [comment] 2019-02-22 12:00
Forget my wish about making that dynamically. There are situations, where a running TYPO3 database is not available. 

So manually adding these storages is just perfect.

**Comment by ursbraem** [comment] 2019-02-28 15:08
I just wanted to post the same question! I always find it a little corny when I spot the "fileadmin" link. And then everybody who knows about TYPO3 knows which CMS is used. I prefer to use `public` and `private` for example.

Yes, manual config would be perfect

**Comment by ursbraem** [comment] 2019-05-23 20:18
@mschwemer is oemmes@40be2dd working so you could make it a Pull request for Helmut?

**Comment by oemmes** [comment] 2019-05-24 06:44
@ursbraem I already submitted this as a pull request but it was not accepted.
See #1

**Comment by ursbraem** [comment] 2019-05-24 08:35
Maybe it was a bit unclear what is meant by core folders. I mean, the use case is very obvious: TYPO3 offers the freedom to set file storages, and thus `fileadmin` shouldn't be hardwired. What do you say @helhum ?

On the other hand, kporras07/composer-symlinks  seems to be a great solution to still get these symlinks into versioning!

**Comment by sascha-egerer** [comment] 2019-07-22 10:39
I think this issue is a duplicate of #6

**Comment by dduers** [comment] 2019-12-07 00:00
> And then everybody who knows about TYPO3 knows which CMS is used.

Well they go to /typo3 and if the login form shows up it's pretty clear anyway ...

**Comment by helhum** [comment] 2020-04-29 09:56
@ursbraem My [comments](https://github.com/helhum/typo3-secure-web/issues/6#issuecomment-355048132) are still valid.

What would make sense though, is not adding a symlink in case the fileadmin folder does not exist.

To allow public local storages in a separate public folder, TYPO3 code should be changed to **not** enforce a storage to be non public, when it isn't a subfolder of PATH_site.

Until this is done, one would still need to provide symlinks for public storages (and hopefully not exposing `uploads`)

**Comment by helhum** [comment] 2020-04-29 10:33
Everybody: Go and test this change: https://review.typo3.org/c/Packages/TYPO3.CMS/+/64345

This enables FAL to properly function when the storage is in public folder:

<img width="566" alt="Screen Shot 2020-04-29 at 12 32 57" src="https://user-images.githubusercontent.com/904370/80586704-a119f280-8a15-11ea-8b3b-42fd3e778475.png">

**Comment by helhum** [comment] 2020-04-29 10:37
With this TYPO3 change merged and the change here, that the fileadmin symlink is only created, when the folder actually exists in the private directory, I think all requirements are fulfilled. 

Or do we still miss something then?

**Comment by helhum** [comment] 2020-05-16 14:34
> and hopefully not exposing uploads

Just realized the upload folder is [gone meanwhile](https://github.com/TYPO3/TYPO3.CMS/commit/780579156bee45782c11ae2ac38ef44cf887bbfa).

**Comment by CDRO** [comment] 2020-08-07 16:30
I think you can close this issue, from my tests, everything worked fine.

**Closed** 2021-01-08 23:46 UTC
