### ISSUE TITLE
Unable to determine path to entry script with v0.2.7

### ISSUE THREAD

**Issue by simonschaufi** [helhum/typo3-secure-web#7] opened 2018-01-01 23:21 UTC
My TYPO3 was running perfectly with v0.2.6 but now i have the problem with `install:generatepackagestates` command.

```
vagrant@homestead:~/Code/typo3-secure-web$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 2 updates, 0 removals
  - Installing typo3/cms-cshmanual (v8.7.9): Downloading (100%)
  - Updating helhum/typo3-composer-setup (v0.4.1 => v0.5.1): Downloading (100%)   - Updating helhum/typo3-secure-web (v0.2.6 => v0.2.7): Downloading (100%)     Writing lock file
Generating autoload files
Registered helhum/dotenv-connector
The class alias map file "Migrations/Code/ClassAliasMap.php" configured in package "typo3/cms-reports" was not found!
Generating  class alias map file
Inserting class alias loader into main autoload.php file
> @php vendor/helhum/typo3-console/Scripts/typo3cms install:generatepackagestates
Unable to determine path to entry script.
Script @php vendor/helhum/typo3-console/Scripts/typo3cms install:generatepackagestates handling the package-states event returned with error code 1
```

here is my composer.json
```
{
	"repositories": [
		{ "type": "path", "url": "packages/*" },
		{ "type": "composer", "url": "https://composer.typo3.org/" }
	],
	"require": {
		"roave/security-advisories": "dev-master",
		"helhum/config-loader": "^0.5.3",
		"helhum/typo3-secure-web": "^0.2.5",
		"helhum/typo3-console": "^4.9",

		"typo3/cms-belog": "^8.7",
		"typo3/cms-beuser": "^8.7",
		"typo3/cms-fluid-styled-content": "^8.7",
		"typo3/cms-info": "^8.7",
		"typo3/cms-info-pagetsconfig": "^8.7",
		"typo3/cms-lowlevel": "^8.7",
		"typo3/cms-reports": "^8.7",
		"typo3/cms-rte-ckeditor": "^8.7",
		"typo3/cms-setup": "^8.7",
		"typo3/cms-sv": "^8.7",
		"typo3/cms-tstemplate": "^8.7",

		"typo3/cms-felogin": "^8.7"
	},
	"require-dev": {
		"helhum/dotenv-connector": "^2.0"
	},
	"scripts": {
		"package-states": [
			"@php vendor/helhum/typo3-console/Scripts/typo3cms install:generatepackagestates"
		],
		"folder-structure": [
			"@php vendor/helhum/typo3-console/Scripts/typo3cms install:fixfolderstructure"
		],
		"pre-deploy": [
			"# Scripts here will be executed by Surf after composer install"
		],
		"post-autoload-dump": [
			"@package-states",
			"@folder-structure"
		]
	},
	"extra": {
		"typo3/cms": {
			"cms-package-dir": "{$vendor-dir}/typo3/cms",
			"root-dir": "typo3",
			"web-dir": "web"
		},
		"helhum/typo3-console": {
			"install-extension-dummy": false
		},
		"helhum/dotenv-connector": {
			"cache-dir": "var/cache"
		}
	}
}
```

**Comment by helhum** [comment] 2018-01-03 15:21
I'm sorry @simonschaufi with this composer.json I cannot reproduce what you report.

Can you try again with just the composer.json you posted and doing a composer install?
Because that is exactly what works for me

**Comment by helhum** [comment] 2018-01-03 15:59
I will close this for now because I'm unable to reproduce. But don't hesitate to comment or re-open when you still struggle

**Closed by helhum** 2018-01-03 15:59 UTC

**Comment by simonschaufi** [comment] 2018-01-04 18:19
works now. don't know why...
